// Get currency symbol based on country
export const getCurrencySymbol = (country: string): string => {
  const currencyMap: { [key: string]: string } = {
    // South Asia
    'India': '₹',
    'Pakistan': '₨',
    'Bangladesh': '৳',
    'Sri Lanka': 'රු',
    'Nepal': 'रु',
    'Bhutan': 'Nu.',
    'Maldives': 'Rf',
    'Afghanistan': '؋',
    
    // North America
    'United States': '$',
    'USA': '$',
    'Canada': 'C$',
    'Mexico': '$',
    'Greenland': 'kr',
    
    // Europe - Western
    'UK': '£',
    'United Kingdom': '£',
    'Germany': '€',
    'France': '€',
    'Italy': '€',
    'Spain': '€',
    'Portugal': '€',
    'Netherlands': '€',
    'Belgium': '€',
    'Austria': '€',
    'Switzerland': 'CHF',
    'Sweden': 'kr',
    'Norway': 'kr',
    'Denmark': 'kr',
    'Finland': '€',
    'Ireland': '€',
    'Luxembourg': '€',
    'Monaco': '€',
    'Liechtenstein': 'CHF',
    'Andorra': '€',
    'San Marino': '€',
    'Vatican City': '€',
    
    // Europe - Eastern
    'Poland': 'zł',
    'Czech Republic': 'Kč',
    'Slovakia': '€',
    'Hungary': 'Ft',
    'Romania': 'lei',
    'Bulgaria': 'лв',
    'Croatia': '€',
    'Serbia': 'дин.',
    'Montenegro': '€',
    'Bosnia and Herzegovina': 'KM',
    'North Macedonia': 'ден',
    'Albania': 'L',
    'Kosovo': '€',
    'Moldova': 'L',
    'Ukraine': '₴',
    'Belarus': 'Br',
    'Russia': '₽',
    'Georgia': '₾',
    'Armenia': '֏',
    'Azerbaijan': '₼',
    'Kazakhstan': '₸',
    
    // Europe - Baltic & Nordic
    'Lithuania': '€',
    'Latvia': '€',
    'Estonia': '€',
    'Iceland': 'kr',
    'Greece': '€',
    'Turkey': '₺',
    'Cyprus': '€',
    'Malta': '€',
    
    // East Asia
    'Japan': '¥',
    'China': '¥',
    'South Korea': '₩',
    'North Korea': '₩',
    'Taiwan': 'NT$',
    'Hong Kong': 'HK$',
    'Macau': 'MOP$',
    'Mongolia': '₮',
    
    // Southeast Asia
    'Indonesia': 'Rp',
    'Malaysia': 'RM',
    'Singapore': 'S$',
    'Thailand': '฿',
    'Vietnam': '₫',
    'Philippines': '₱',
    'Myanmar': 'K',
    'Cambodia': '៛',
    'Laos': '₭',
    'Brunei': 'B$',
    'East Timor': '$',
    
    // Central Asia
    'Uzbekistan': 'soʻm',
    'Turkmenistan': 'm',
    'Kyrgyzstan': 'som',
    'Tajikistan': 'SM',
    
    // Middle East
    'UAE': 'د.إ',
    'United Arab Emirates': 'د.إ',
    'Saudi Arabia': '﷼',
    'Qatar': '﷼',
    'Kuwait': 'د.ك',
    'Bahrain': '.د.ب',
    'Oman': '﷼',
    'Jordan': 'د.ا',
    'Lebanon': 'ل.ل',
    'Israel': '₪',
    'Iran': '﷼',
    'Iraq': 'ع.د',
    'Syria': 'ل.س',
    'Yemen': '﷼',
    'Palestine': '₪',
    
    // Oceania
    'Australia': 'A$',
    'New Zealand': 'NZ$',
    'Fiji': 'FJ$',
    'Papua New Guinea': 'K',
    'Solomon Islands': 'SI$',
    'Vanuatu': 'VT',
    'Samoa': 'T',
    'Tonga': 'T$',
    'Kiribati': '$',
    'Marshall Islands': '$',
    'Micronesia': '$',
    'Palau': '$',
    'Nauru': '$',
    'Tuvalu': '$',
    'Cook Islands': '$',
    
    // South America
    'Brazil': 'R$',
    'Argentina': '$',
    'Chile': '$',
    'Peru': 'S/',
    'Colombia': '$',
    'Venezuela': 'Bs',
    'Ecuador': '$',
    'Uruguay': '$',
    'Paraguay': '₲',
    'Bolivia': 'Bs.',
    'Guyana': 'G$',
    'Suriname': '$',
    'French Guiana': '€',
    
    // Central America
    'Guatemala': 'Q',
    'Honduras': 'L',
    'El Salvador': '$',
    'Nicaragua': 'C$',
    'Costa Rica': '₡',
    'Panama': 'B/.',
    
    // Caribbean
    'Cuba': '$',
    'Jamaica': 'J$',
    'Haiti': 'G',
    'Dominican Republic': 'RD$',
    'Puerto Rico': '$',
    'Bahamas': 'B$',
    'Trinidad and Tobago': 'TT$',
    'Barbados': 'Bds$',
    'Saint Lucia': 'EC$',
    'Grenada': 'EC$',
    'Saint Vincent and the Grenadines': 'EC$',
    'Antigua and Barbuda': 'EC$',
    'Dominica': 'EC$',
    'Saint Kitts and Nevis': 'EC$',
    'Belize': 'BZ$',
    
    // Africa - North
    'South Africa': 'R',
    'Egypt': 'E£',
    'Morocco': 'د.م.',
    'Algeria': 'د.ج',
    'Tunisia': 'د.ت',
    'Libya': 'ل.د',
    'Sudan': 'ج.س.',
    'South Sudan': 'SSP',
    'Western Sahara': 'د.م.',
    
    // Africa - West
    'Nigeria': '₦',
    'Ghana': '₵',
    'Ivory Coast': 'FCFA',
    'Senegal': 'FCFA',
    'Mali': 'FCFA',
    'Burkina Faso': 'FCFA',
    'Benin': 'FCFA',
    'Guinea': 'FG',
    'Guinea-Bissau': 'FCFA',
    'Liberia': '$',
    'Sierra Leone': 'Le',
    'Togo': 'FCFA',
    'Cape Verde': 'Esc',
    'Mauritania': 'UM',
    'Gambia': 'D',
    
    // Africa - East
    'Kenya': 'KSh',
    'Tanzania': 'TSh',
    'Uganda': 'USh',
    'Rwanda': 'FRw',
    'Burundi': 'FBu',
    'Ethiopia': 'Br',
    'Eritrea': 'Nfk',
    'Djibouti': 'Fdj',
    'Somalia': 'SOS',
    'Somaliland': 'SlSh',
    'Comoros': 'CF',
    'Mauritius': '₨',
    'Seychelles': 'SR',
    
    // Africa - Central
    'Cameroon': 'FCFA',
    'Chad': 'FCFA',
    'Central African Republic': 'FCFA',
    'Equatorial Guinea': 'FCFA',
    'Gabon': 'FCFA',
    'Republic of Congo': 'FCFA',
    'Democratic Republic of Congo': 'FC',
    'Sao Tome and Principe': 'Db',
    
    // Africa - South
    'Angola': 'Kz',
    'Namibia': '$',
    'Botswana': 'P',
    'Zambia': 'ZK',
    'Zimbabwe': '$',
    'Malawi': 'MK',
    'Mozambique': 'MT',
    'Madagascar': 'Ar',
    'Lesotho': 'L',
    'Eswatini': 'L',
    
    // Default EU and Europe
    'Europe': '€',
    'EU': '€',
  };
  
  // Default to $ if country not found
  return currencyMap[country] || '$';
};